-- -- Plugins that are related to coding. Such as lsp
-- -- or language specific.
-- return {
--   {
--     "neovim/nvim-lspconfig",
--     event = "VeryLazy",
--     config = function()
--       require("plugins.configs.lspconfig")
--     end,
--   },
--   {
--     "williamboman/mason.nvim",
--     cmd = { "Mason", "MasonInstall", "MasonInstallAll", "MasonUpdate" },
--     opts = function()
--       return require("plugins.configs.mason")
--     end,
--     config = function(_, opts)
--       require("mason").setup(opts)

--       vim.api.nvim_create_user_command("MasonInstallAll", function()
--         if opts.ensure_installed then
--           vim.cmd("MasonInstall " .. table.concat(opts.ensure_installed, " "))
--         end
--       end, {})

--       vim.g.mason_binaries_list = opts.ensure_installed
--     end,
--   },
-- }
